In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
original_df = pd.read_excel("D:\Oct_23\sales_cable.xlsx")
original_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SL.,Trader's Name,Party Type,Trader's Address,Outstanding,Sales (BDT.),Sales Return (BDT.),Collection (BDT.),Current Outstanding(BDT.),Branch_name
2,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
3,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
4,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0,0,-0.14,Ashulia Sales Center
...,...,...,...,...,...,...,...,...,...,...
4106,4105,Vai-Vai Electric,Traders,"Station Road, Ishwardi",564053.42,441038.4,0,365000,640091.82,Ishwardi Sales Center
4107,4106,Vai-Vai Electric & Electronicss,Traders,"Station Road, Muladuli, Ishwardi.",0,0,0,0,0,Ishwardi Sales Center
4108,4107,Vai-Vai Hardware,Traders,"Joynagor, Shemultola, Ishwardi",-0.64,0,0,0,-0.64,Ishwardi Sales Center
4109,4108,Vai-Vai Hardware & Electric House,Traders,Khidirpur Bazar.,-0.08,0,0,0,-0.08,Ishwardi Sales Center
4110,4109,Wasim Electric & Electronics,Traders,"Chorgorgori Alhaz More, Ishwardi.",-7.05,0,0,0,-7.05,Ishwardi Sales Center

In [20]:
original_df.shape

(4111, 10)

In [21]:
#dd.mm.yy
path = "D:\Oct_23\cable_trader_oct_date 25.10.23.xlsx"
path

'D:\\Oct_23\\cable_trader_oct_date 25.10.23.xlsx'

In [22]:
date1 = path.split('_')
date1

['D:\\Oct', '23\\cable', 'trader', 'oct', 'date 25.10.23.xlsx']

In [23]:
date1 = path.split('_')[-1]
date1

'date 25.10.23.xlsx'

In [24]:
date1 = path.split('_')[-1].split(' ')
date1

['date', '25.10.23.xlsx']

In [25]:
date1 = path.split('_')[-1].split(' ')[-1]
date1

'25.10.23.xlsx'

In [26]:
date1 = path.split('_')[-1].split(' ')[-1].split('.')
date1

['25', '10', '23', 'xlsx']

In [27]:
date = path.split('_')[-1].split(' ')[-1].split('.')[0]
date

'25'

In [28]:
month = path.split('_')[-1].split(' ')[-1].split('.')[1]
month

'10'

In [29]:
year = path.split('_')[-1].split(' ')[-1].split('.')[2]
year

'23'

In [30]:
date_contruction = f'{year}-{month}-{date}'
date_contruction

'23-10-25'

In [31]:
path

'D:\\Oct_23\\cable_trader_oct_date 25.10.23.xlsx'

In [32]:
# Summary
# first split by _ then index then split by space & index then split by & index
date = path.split('_')[-1].split(' ')[-1].split('.')[0]
month = path.split('_')[-1].split(' ')[-1].split('.')[1]
year = path.split('_')[-1].split(' ')[-1].split('.')[2]

# Date Contrcution
date_contruction = f'{year}-{month}-{date}'
date_contruction

'23-10-25'

In [33]:
df1 = original_df.iloc[:, :7]
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SL.,Trader's Name,Party Type,Trader's Address,Outstanding,Sales (BDT.),Sales Return (BDT.)
2,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0
3,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0
4,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0
...,...,...,...,...,...,...,...
4106,4105,Vai-Vai Electric,Traders,"Station Road, Ishwardi",564053.42,441038.4,0
4107,4106,Vai-Vai Electric & Electronicss,Traders,"Station Road, Muladuli, Ishwardi.",0,0,0
4108,4107,Vai-Vai Hardware,Traders,"Joynagor, Shemultola, Ishwardi",-0.64,0,0
4109,4108,Vai-Vai Hardware & Electric House,Traders,Khidirpur Bazar.,-0.08,0,0
4110,4109,Wasim Electric & Electronics,Traders,"Chorgorgori Alhaz More, Ishwardi.",-7.05,0,0

In [34]:
df = original_df[]
df

SyntaxError: invalid syntax (1280508376.py, line 1)

In [35]:
df = original_df[]

SyntaxError: invalid syntax (1015122402.py, line 1)

In [36]:
original_df2 = pd.read_excel("D:\Oct_23\sales_cable.xlsx", header = None) # header = None > remomving unnamed column
original_df2

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SL.,Trader's Name,Party Type,Trader's Address,Outstanding,Sales (BDT.),Sales Return (BDT.),Collection (BDT.),Current Outstanding(BDT.),Branch_name
3,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
4,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
...,...,...,...,...,...,...,...,...,...,...
4107,4105,Vai-Vai Electric,Traders,"Station Road, Ishwardi",564053.42,441038.4,0,365000,640091.82,Ishwardi Sales Center
4108,4106,Vai-Vai Electric & Electronicss,Traders,"Station Road, Muladuli, Ishwardi.",0,0,0,0,0,Ishwardi Sales Center
4109,4107,Vai-Vai Hardware,Traders,"Joynagor, Shemultola, Ishwardi",-0.64,0,0,0,-0.64,Ishwardi Sales Center
4110,4108,Vai-Vai Hardware & Electric House,Traders,Khidirpur Bazar.,-0.08,0,0,0,-0.08,Ishwardi Sales Center
4111,4109,Wasim Electric & Electronics,Traders,"Chorgorgori Alhaz More, Ishwardi.",-7.05,0,0,0,-7.05,Ishwardi Sales Center

In [37]:
original_df3 = original_df2[2:]
original_df3

,0,1,2,3,4,5,6,7,8,9
2,SL.,Trader's Name,Party Type,Trader's Address,Outstanding,Sales (BDT.),Sales Return (BDT.),Collection (BDT.),Current Outstanding(BDT.),Branch_name
3,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
4,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
5,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0,0,-0.14,Ashulia Sales Center
6,4,Akhi Electric,Traders,"Super Market,Ashulia Bazar,Ashulia.",-0.65,0,0,0,-0.65,Ashulia Sales Center
...,...,...,...,...,...,...,...,...,...,...
4107,4105,Vai-Vai Electric,Traders,"Station Road, Ishwardi",564053.42,441038.4,0,365000,640091.82,Ishwardi Sales Center
4108,4106,Vai-Vai Electric & Electronicss,Traders,"Station Road, Muladuli, Ishwardi.",0,0,0,0,0,Ishwardi Sales Center
4109,4107,Vai-Vai Hardware,Traders,"Joynagor, Shemultola, Ishwardi",-0.64,0,0,0,-0.64,Ishwardi Sales Center
4110,4108,Vai-Vai Hardware & Electric House,Traders,Khidirpur Bazar.,-0.08,0,0,0,-0.08,Ishwardi Sales Center
4111,4109,Wasim Electric & Electronics,Traders,"Chorgorgori Alhaz More, Ishwardi.",-7.05,0,0,0,-7.05,Ishwardi Sales Center

In [38]:
original_df4 = original_df2[3:]
original_df4

,0,1,2,3,4,5,6,7,8,9
3,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
4,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
5,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0,0,-0.14,Ashulia Sales Center
6,4,Akhi Electric,Traders,"Super Market,Ashulia Bazar,Ashulia.",-0.65,0,0,0,-0.65,Ashulia Sales Center
7,5,Al Modina Electric,Traders,"Katal Bagan,Polash Bare,Ashulia",-1.77,0,0,0,-1.77,Ashulia Sales Center
...,...,...,...,...,...,...,...,...,...,...
4107,4105,Vai-Vai Electric,Traders,"Station Road, Ishwardi",564053.42,441038.4,0,365000,640091.82,Ishwardi Sales Center
4108,4106,Vai-Vai Electric & Electronicss,Traders,"Station Road, Muladuli, Ishwardi.",0,0,0,0,0,Ishwardi Sales Center
4109,4107,Vai-Vai Hardware,Traders,"Joynagor, Shemultola, Ishwardi",-0.64,0,0,0,-0.64,Ishwardi Sales Center
4110,4108,Vai-Vai Hardware & Electric House,Traders,Khidirpur Bazar.,-0.08,0,0,0,-0.08,Ishwardi Sales Center
4111,4109,Wasim Electric & Electronics,Traders,"Chorgorgori Alhaz More, Ishwardi.",-7.05,0,0,0,-7.05,Ishwardi Sales Center

In [39]:
df3 = original_df4.rename(columns ={0:'SL', 1:'trader_name', 2:'party_type', 3:'address', 4:'opening', 5:'sales', 
                                   6:'return', 7:'collectoin', 8:'closing', 9:'branch_name'
                                   })
df3.head()

,SL,trader_name,party_type,address,opening,sales,return,collectoin,closing,branch_name
3,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
4,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
5,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0,0,-0.14,Ashulia Sales Center
6,4,Akhi Electric,Traders,"Super Market,Ashulia Bazar,Ashulia.",-0.65,0,0,0,-0.65,Ashulia Sales Center
7,5,Al Modina Electric,Traders,"Katal Bagan,Polash Bare,Ashulia",-1.77,0,0,0,-1.77,Ashulia Sales Center

In [45]:
df5 = pd.read_excel("D:\Oct_23\sales_cable.xlsx",index_col=None, header=0)
df5.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SL.,Trader's Name,Party Type,Trader's Address,Outstanding,Sales (BDT.),Sales Return (BDT.),Collection (BDT.),Current Outstanding(BDT.),Branch_name
2,1,A J Electric (Vadail),Traders,"School Road,Vadail.",132809.18,0,0,0,132809.18,Ashulia Sales Center
3,2,Afroz Electric,Traders,"Chowdhury Market, Chowrasta, Ashulia, Dhaka.",-551.56,0,0,0,-551.56,Ashulia Sales Center
4,3,Afsana Enterprise,Traders,"Landmark,Ashulia",-0.14,0,0,0,-0.14,Ashulia Sales Center